name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate JSON files
      run: |
        find . -name "*.json" -exec python3 -m json.tool {} \; > /dev/null 2>&1 || exit 1

    - name: Package distributables
      shell: pwsh
      run: ./tools/package.ps1

    - uses: actions/upload-artifact@v4
      with:
        name: futureverse-artifacts
        path: dist/*
